version: 2

models:

    - name: date_dimension
      description: "date_dimension"
      columns:
        - name: d_date
          description: "The primary key for this table"
          tests:
              - unique
              - not_null
    - name: scd_testing

sources:
  - name: sf_sample_data
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
    tables:
      - name: date_dim
        columns:
          - name: d_date
            tests:
              - unique
              - not_null

